# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0749f96aef00e5853bd8c03ae92191c2000661b6ceb69fc7cc96189146f925ac6bc37487359004bd375f359fff5a9ce93f72f8f861a8b3b807c3e50c654c74af

test:
  secret_key_base: 580382d41dbc3518691b7683194908dd73e49d2b66772bc0477be55497ac8331c6a4faac7395efa03bb05a3af8adecc9b5e3f5a54e49250d9d56403efa759cdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
